name = "boi-gordo-mcp"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

# Bindings para KV namespaces se necessário
# [[kv_namespaces]]
# binding = "DIAGNOSTICS"
# id = "your-kv-namespace-id"

# Configuração de CORS
[env.production.vars]
ALLOWED_ORIGINS = "https://fb0cfd9c.plataforma-futuros.pages.dev,https://plataforma-futuros.pages.dev"
MCP_AUTH_TOKEN = "boi-gordo-mcp-2024-secure-token"