name = "boi-gordo-mcp"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Variáveis de ambiente
[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "https://fb0cfd9c.plataforma-futuros.pages.dev,https://plataforma-futuros.pages.dev"
MCP_AUTH_TOKEN = "boi-gordo-mcp-2024-secure-token"
NEXT_PUBLIC_SUPABASE_URL = "https://kdfevkbwohcajcwrqzor.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkZmV2a2J3b2hjYWpjd3Jxem9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTUzODcsImV4cCI6MjA2ODg5MTM4N30.4nBjKi3rdpfbYmxeoa8GELdBLq8JY6ym68cJX7jpaus"

# Bindings para KV namespaces se necessário
# [[kv_namespaces]]
# binding = "DIAGNOSTICS"
# id = "your-kv-namespace-id"