name = "boi-gordo-mcp-official"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

# Configurações de CORS
ALLOWED_ORIGINS = "*"

# Variáveis do Supabase (serão adicionadas como secrets em produção)
# SUPABASE_URL = "https://kdfevkbwohcajcwrqzor.supabase.co"
# SUPABASE_ANON_KEY = "..."